
sparkmaster:
  image: gettyimages/spark:1.4.1-hadoop-2.6
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.master.Master --ip master
  hostname: master
  environment:
    SPARK_CONF_DIR: /conf
  ports:
    - "4040:4040"
    - "6066:6066"
    - "7077:7077"
    - "8080:8080"
  volumes:
    - ./conf/master:/conf
    - ./data:/tmp/data

sparkworker:
  image: gettyimages/spark:1.4.1-hadoop-2.6
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 1
    SPARK_WORKER_MEMORY: 1g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - kafka
    - sparkmaster
    - cassandra
  ports:
    - "8081"
  volumes:
    - ./conf/worker:/conf
    - ./data:/tmp/data